/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __SYNCE_DEVICE_MANAGER_DBUS_H__
#define __SYNCE_DEVICE_MANAGER_DBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.synce.dccm.DeviceManager */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER (synce_dbus_device_manager_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER, SynceDbusDeviceManager))
#define SYNCE_DBUS_IS_DEVICE_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER))
#define SYNCE_DBUS_DEVICE_MANAGER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER, SynceDbusDeviceManagerIface))

struct _SynceDbusDeviceManager;
typedef struct _SynceDbusDeviceManager SynceDbusDeviceManager;
typedef struct _SynceDbusDeviceManagerIface SynceDbusDeviceManagerIface;

struct _SynceDbusDeviceManagerIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_connected_devices) (
    SynceDbusDeviceManager *object,
    GDBusMethodInvocation *invocation);

  void (*device_connected) (
    SynceDbusDeviceManager *object,
    const gchar *arg_name);

  void (*device_disconnected) (
    SynceDbusDeviceManager *object,
    const gchar *arg_name);

};

GType synce_dbus_device_manager_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *synce_dbus_device_manager_interface_info (void);
guint synce_dbus_device_manager_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void synce_dbus_device_manager_complete_get_connected_devices (
    SynceDbusDeviceManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *device_list);



/* D-Bus signal emissions functions: */
void synce_dbus_device_manager_emit_device_connected (
    SynceDbusDeviceManager *object,
    const gchar *arg_name);

void synce_dbus_device_manager_emit_device_disconnected (
    SynceDbusDeviceManager *object,
    const gchar *arg_name);



/* D-Bus method calls: */
void synce_dbus_device_manager_call_get_connected_devices (
    SynceDbusDeviceManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_manager_call_get_connected_devices_finish (
    SynceDbusDeviceManager *proxy,
    gchar ***out_device_list,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_manager_call_get_connected_devices_sync (
    SynceDbusDeviceManager *proxy,
    gchar ***out_device_list,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY (synce_dbus_device_manager_proxy_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY, SynceDbusDeviceManagerProxy))
#define SYNCE_DBUS_DEVICE_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY, SynceDbusDeviceManagerProxyClass))
#define SYNCE_DBUS_DEVICE_MANAGER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY, SynceDbusDeviceManagerProxyClass))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_PROXY))

typedef struct _SynceDbusDeviceManagerProxy SynceDbusDeviceManagerProxy;
typedef struct _SynceDbusDeviceManagerProxyClass SynceDbusDeviceManagerProxyClass;
typedef struct _SynceDbusDeviceManagerProxyPrivate SynceDbusDeviceManagerProxyPrivate;

struct _SynceDbusDeviceManagerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  SynceDbusDeviceManagerProxyPrivate *priv;
};

struct _SynceDbusDeviceManagerProxyClass
{
  GDBusProxyClass parent_class;
};

GType synce_dbus_device_manager_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceManagerProxy, g_object_unref)
#endif

void synce_dbus_device_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDeviceManager *synce_dbus_device_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDeviceManager *synce_dbus_device_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void synce_dbus_device_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDeviceManager *synce_dbus_device_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDeviceManager *synce_dbus_device_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON (synce_dbus_device_manager_skeleton_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON, SynceDbusDeviceManagerSkeleton))
#define SYNCE_DBUS_DEVICE_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON, SynceDbusDeviceManagerSkeletonClass))
#define SYNCE_DBUS_DEVICE_MANAGER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON, SynceDbusDeviceManagerSkeletonClass))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_SKELETON))

typedef struct _SynceDbusDeviceManagerSkeleton SynceDbusDeviceManagerSkeleton;
typedef struct _SynceDbusDeviceManagerSkeletonClass SynceDbusDeviceManagerSkeletonClass;
typedef struct _SynceDbusDeviceManagerSkeletonPrivate SynceDbusDeviceManagerSkeletonPrivate;

struct _SynceDbusDeviceManagerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  SynceDbusDeviceManagerSkeletonPrivate *priv;
};

struct _SynceDbusDeviceManagerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType synce_dbus_device_manager_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceManagerSkeleton, g_object_unref)
#endif

SynceDbusDeviceManager *synce_dbus_device_manager_skeleton_new (void);


G_END_DECLS

#endif /* __SYNCE_DEVICE_MANAGER_DBUS_H__ */
