/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __SYNCE_DEVICE_MANAGER_CONTROL_MARSHAL_MARSHAL_H__
#define __SYNCE_DEVICE_MANAGER_CONTROL_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING,STRING,STRING,BOOLEAN (synce-device-manager-control-signals-marshal.list:1) */
extern
void synce_device_manager_control_marshal_VOID__STRING_STRING_STRING_BOOLEAN (GClosure     *closure,
                                                                              GValue       *return_value,
                                                                              guint         n_param_values,
                                                                              const GValue *param_values,
                                                                              gpointer      invocation_hint,
                                                                              gpointer      marshal_data);


G_END_DECLS

#endif /* __SYNCE_DEVICE_MANAGER_CONTROL_MARSHAL_MARSHAL_H__ */
