/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __SYNCE_DEVICE_MANAGER_CONTROL_DBUS_H__
#define __SYNCE_DEVICE_MANAGER_CONTROL_DBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.synce.dccm.DeviceManager.Control */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL (synce_dbus_device_manager_control_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL, SynceDbusDeviceManagerControl))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_CONTROL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL))
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL, SynceDbusDeviceManagerControlIface))

struct _SynceDbusDeviceManagerControl;
typedef struct _SynceDbusDeviceManagerControl SynceDbusDeviceManagerControl;
typedef struct _SynceDbusDeviceManagerControlIface SynceDbusDeviceManagerControlIface;

struct _SynceDbusDeviceManagerControlIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_device_connected) (
    SynceDbusDeviceManagerControl *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device_path,
    const gchar *arg_device_ip,
    const gchar *arg_local_ip,
    gboolean arg_rndis);

  gboolean (*handle_device_disconnected) (
    SynceDbusDeviceManagerControl *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device_path);

};

GType synce_dbus_device_manager_control_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *synce_dbus_device_manager_control_interface_info (void);
guint synce_dbus_device_manager_control_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void synce_dbus_device_manager_control_complete_device_connected (
    SynceDbusDeviceManagerControl *object,
    GDBusMethodInvocation *invocation);

void synce_dbus_device_manager_control_complete_device_disconnected (
    SynceDbusDeviceManagerControl *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void synce_dbus_device_manager_control_call_device_connected (
    SynceDbusDeviceManagerControl *proxy,
    const gchar *arg_device_path,
    const gchar *arg_device_ip,
    const gchar *arg_local_ip,
    gboolean arg_rndis,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_manager_control_call_device_connected_finish (
    SynceDbusDeviceManagerControl *proxy,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_manager_control_call_device_connected_sync (
    SynceDbusDeviceManagerControl *proxy,
    const gchar *arg_device_path,
    const gchar *arg_device_ip,
    const gchar *arg_local_ip,
    gboolean arg_rndis,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_manager_control_call_device_disconnected (
    SynceDbusDeviceManagerControl *proxy,
    const gchar *arg_device_path,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_manager_control_call_device_disconnected_finish (
    SynceDbusDeviceManagerControl *proxy,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_manager_control_call_device_disconnected_sync (
    SynceDbusDeviceManagerControl *proxy,
    const gchar *arg_device_path,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY (synce_dbus_device_manager_control_proxy_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY, SynceDbusDeviceManagerControlProxy))
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY, SynceDbusDeviceManagerControlProxyClass))
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY, SynceDbusDeviceManagerControlProxyClass))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_CONTROL_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_CONTROL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_PROXY))

typedef struct _SynceDbusDeviceManagerControlProxy SynceDbusDeviceManagerControlProxy;
typedef struct _SynceDbusDeviceManagerControlProxyClass SynceDbusDeviceManagerControlProxyClass;
typedef struct _SynceDbusDeviceManagerControlProxyPrivate SynceDbusDeviceManagerControlProxyPrivate;

struct _SynceDbusDeviceManagerControlProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  SynceDbusDeviceManagerControlProxyPrivate *priv;
};

struct _SynceDbusDeviceManagerControlProxyClass
{
  GDBusProxyClass parent_class;
};

GType synce_dbus_device_manager_control_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceManagerControlProxy, g_object_unref)
#endif

void synce_dbus_device_manager_control_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDeviceManagerControl *synce_dbus_device_manager_control_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDeviceManagerControl *synce_dbus_device_manager_control_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void synce_dbus_device_manager_control_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDeviceManagerControl *synce_dbus_device_manager_control_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDeviceManagerControl *synce_dbus_device_manager_control_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON (synce_dbus_device_manager_control_skeleton_get_type ())
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON, SynceDbusDeviceManagerControlSkeleton))
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON, SynceDbusDeviceManagerControlSkeletonClass))
#define SYNCE_DBUS_DEVICE_MANAGER_CONTROL_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON, SynceDbusDeviceManagerControlSkeletonClass))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_CONTROL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON))
#define SYNCE_DBUS_IS_DEVICE_MANAGER_CONTROL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_MANAGER_CONTROL_SKELETON))

typedef struct _SynceDbusDeviceManagerControlSkeleton SynceDbusDeviceManagerControlSkeleton;
typedef struct _SynceDbusDeviceManagerControlSkeletonClass SynceDbusDeviceManagerControlSkeletonClass;
typedef struct _SynceDbusDeviceManagerControlSkeletonPrivate SynceDbusDeviceManagerControlSkeletonPrivate;

struct _SynceDbusDeviceManagerControlSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  SynceDbusDeviceManagerControlSkeletonPrivate *priv;
};

struct _SynceDbusDeviceManagerControlSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType synce_dbus_device_manager_control_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceManagerControlSkeleton, g_object_unref)
#endif

SynceDbusDeviceManagerControl *synce_dbus_device_manager_control_skeleton_new (void);


G_END_DECLS

#endif /* __SYNCE_DEVICE_MANAGER_CONTROL_DBUS_H__ */
