/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __SYNCE_DEVICE_DBUS_H__
#define __SYNCE_DEVICE_DBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.synce.dccm.Device */

#define SYNCE_DBUS_TYPE_DEVICE (synce_dbus_device_get_type ())
#define SYNCE_DBUS_DEVICE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE, SynceDbusDevice))
#define SYNCE_DBUS_IS_DEVICE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE))
#define SYNCE_DBUS_DEVICE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), SYNCE_DBUS_TYPE_DEVICE, SynceDbusDeviceIface))

struct _SynceDbusDevice;
typedef struct _SynceDbusDevice SynceDbusDevice;
typedef struct _SynceDbusDeviceIface SynceDbusDeviceIface;

struct _SynceDbusDeviceIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_cpu_type) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_current_partner_id) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_guid) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_iface_address) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_ip_address) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_model_name) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_name) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_os_version) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_password_flags) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_platform_name) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_version) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_provide_password) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_password);

  gboolean (*handle_request_connection) (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation);

  void (*password_flags_changed) (
    SynceDbusDevice *object,
    const gchar *arg_flag);

};

GType synce_dbus_device_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *synce_dbus_device_interface_info (void);
guint synce_dbus_device_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void synce_dbus_device_complete_get_name (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *name);

void synce_dbus_device_complete_get_platform_name (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *platform_name);

void synce_dbus_device_complete_get_model_name (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *model_name);

void synce_dbus_device_complete_get_os_version (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    guint os_major,
    guint os_minor);

void synce_dbus_device_complete_get_version (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    guint version);

void synce_dbus_device_complete_get_cpu_type (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    guint cpu_type);

void synce_dbus_device_complete_get_ip_address (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *ip_address);

void synce_dbus_device_complete_get_iface_address (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *iface_address);

void synce_dbus_device_complete_get_guid (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *guid);

void synce_dbus_device_complete_get_password_flags (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *pw_flags);

void synce_dbus_device_complete_get_current_partner_id (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    guint cur_partner_id);

void synce_dbus_device_complete_provide_password (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    gboolean unnamed_arg1);

void synce_dbus_device_complete_request_connection (
    SynceDbusDevice *object,
    GDBusMethodInvocation *invocation,
    const gchar *unix_socket_path);



/* D-Bus signal emissions functions: */
void synce_dbus_device_emit_password_flags_changed (
    SynceDbusDevice *object,
    const gchar *arg_flag);



/* D-Bus method calls: */
void synce_dbus_device_call_get_name (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_name_finish (
    SynceDbusDevice *proxy,
    gchar **out_name,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_name_sync (
    SynceDbusDevice *proxy,
    gchar **out_name,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_platform_name (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_platform_name_finish (
    SynceDbusDevice *proxy,
    gchar **out_platform_name,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_platform_name_sync (
    SynceDbusDevice *proxy,
    gchar **out_platform_name,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_model_name (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_model_name_finish (
    SynceDbusDevice *proxy,
    gchar **out_model_name,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_model_name_sync (
    SynceDbusDevice *proxy,
    gchar **out_model_name,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_os_version (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_os_version_finish (
    SynceDbusDevice *proxy,
    guint *out_os_major,
    guint *out_os_minor,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_os_version_sync (
    SynceDbusDevice *proxy,
    guint *out_os_major,
    guint *out_os_minor,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_version (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_version_finish (
    SynceDbusDevice *proxy,
    guint *out_version,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_version_sync (
    SynceDbusDevice *proxy,
    guint *out_version,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_cpu_type (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_cpu_type_finish (
    SynceDbusDevice *proxy,
    guint *out_cpu_type,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_cpu_type_sync (
    SynceDbusDevice *proxy,
    guint *out_cpu_type,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_ip_address (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_ip_address_finish (
    SynceDbusDevice *proxy,
    gchar **out_ip_address,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_ip_address_sync (
    SynceDbusDevice *proxy,
    gchar **out_ip_address,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_iface_address (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_iface_address_finish (
    SynceDbusDevice *proxy,
    gchar **out_iface_address,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_iface_address_sync (
    SynceDbusDevice *proxy,
    gchar **out_iface_address,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_guid (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_guid_finish (
    SynceDbusDevice *proxy,
    gchar **out_guid,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_guid_sync (
    SynceDbusDevice *proxy,
    gchar **out_guid,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_password_flags (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_password_flags_finish (
    SynceDbusDevice *proxy,
    gchar **out_pw_flags,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_password_flags_sync (
    SynceDbusDevice *proxy,
    gchar **out_pw_flags,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_get_current_partner_id (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_get_current_partner_id_finish (
    SynceDbusDevice *proxy,
    guint *out_cur_partner_id,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_get_current_partner_id_sync (
    SynceDbusDevice *proxy,
    guint *out_cur_partner_id,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_provide_password (
    SynceDbusDevice *proxy,
    const gchar *arg_password,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_provide_password_finish (
    SynceDbusDevice *proxy,
    gboolean *out_unnamed_arg1,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_provide_password_sync (
    SynceDbusDevice *proxy,
    const gchar *arg_password,
    gboolean *out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void synce_dbus_device_call_request_connection (
    SynceDbusDevice *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean synce_dbus_device_call_request_connection_finish (
    SynceDbusDevice *proxy,
    gchar **out_unix_socket_path,
    GAsyncResult *res,
    GError **error);

gboolean synce_dbus_device_call_request_connection_sync (
    SynceDbusDevice *proxy,
    gchar **out_unix_socket_path,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_PROXY (synce_dbus_device_proxy_get_type ())
#define SYNCE_DBUS_DEVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_PROXY, SynceDbusDeviceProxy))
#define SYNCE_DBUS_DEVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_PROXY, SynceDbusDeviceProxyClass))
#define SYNCE_DBUS_DEVICE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_PROXY, SynceDbusDeviceProxyClass))
#define SYNCE_DBUS_IS_DEVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_PROXY))
#define SYNCE_DBUS_IS_DEVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_PROXY))

typedef struct _SynceDbusDeviceProxy SynceDbusDeviceProxy;
typedef struct _SynceDbusDeviceProxyClass SynceDbusDeviceProxyClass;
typedef struct _SynceDbusDeviceProxyPrivate SynceDbusDeviceProxyPrivate;

struct _SynceDbusDeviceProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  SynceDbusDeviceProxyPrivate *priv;
};

struct _SynceDbusDeviceProxyClass
{
  GDBusProxyClass parent_class;
};

GType synce_dbus_device_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceProxy, g_object_unref)
#endif

void synce_dbus_device_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDevice *synce_dbus_device_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDevice *synce_dbus_device_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void synce_dbus_device_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SynceDbusDevice *synce_dbus_device_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
SynceDbusDevice *synce_dbus_device_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define SYNCE_DBUS_TYPE_DEVICE_SKELETON (synce_dbus_device_skeleton_get_type ())
#define SYNCE_DBUS_DEVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SYNCE_DBUS_TYPE_DEVICE_SKELETON, SynceDbusDeviceSkeleton))
#define SYNCE_DBUS_DEVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SYNCE_DBUS_TYPE_DEVICE_SKELETON, SynceDbusDeviceSkeletonClass))
#define SYNCE_DBUS_DEVICE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SYNCE_DBUS_TYPE_DEVICE_SKELETON, SynceDbusDeviceSkeletonClass))
#define SYNCE_DBUS_IS_DEVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SYNCE_DBUS_TYPE_DEVICE_SKELETON))
#define SYNCE_DBUS_IS_DEVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SYNCE_DBUS_TYPE_DEVICE_SKELETON))

typedef struct _SynceDbusDeviceSkeleton SynceDbusDeviceSkeleton;
typedef struct _SynceDbusDeviceSkeletonClass SynceDbusDeviceSkeletonClass;
typedef struct _SynceDbusDeviceSkeletonPrivate SynceDbusDeviceSkeletonPrivate;

struct _SynceDbusDeviceSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  SynceDbusDeviceSkeletonPrivate *priv;
};

struct _SynceDbusDeviceSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType synce_dbus_device_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SynceDbusDeviceSkeleton, g_object_unref)
#endif

SynceDbusDevice *synce_dbus_device_skeleton_new (void);


G_END_DECLS

#endif /* __SYNCE_DEVICE_DBUS_H__ */
