#!/bin/sh

logger -p daemon.info -t synce-udev-serial "INFO : serial event, ACTION = $ACTION, INTERFACE = $INTERFACE, DEVPATH = $DEVPATH, SUBSYSTEM = $SUBSYSTEM, DEVNAME = $DEVNAME"

/usr/local/share/synce-core/udev-synce-serial &

exit 0
